version: '3'

services:
  spring-boot-rest-api-app:
    image: springboot-docker-compose-app
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    volumes:
      - /data/springboot-docker-compose-app