FROM java:8
LABEL maintainer=“Prem.Kumar4@mindtree.com”
WORKDIR /app
COPY target/springbootsample-0.0.1-SNAPSHOT.jar /app/springbootsample-0.0.1-SNAPSHOT.jar
ENTRYPOINT ["java","-jar","springbootsample-0.0.1-SNAPSHOT.jar"]